### ISSUE TITLE
Unable to load the edk library on Windows 8 x64

### ISSUE THREAD

**Issue by MartinsIrbe** [Emotiv/community-sdk#155]
`"C:\Program Files\Java\jdk1.8.0_111\bin\java" -Djava.library.path=C:\dev\eegproject\src\main\res\win64 -Didea.launcher.port=7535 "-Didea.launcher.bin.path=C:\Program Files (x86)\JetBrains\IntelliJ IDEA Community Edition 2016.3\bin" -Dfile.encoding=UTF-8 -classpath "C:\Program Files\Java\jdk1.8.0_111\jre\lib\charsets.jar;C:\Program Files\Java\jdk1.8.0_111\jre\lib\deploy.jar;C:\Program Files\Java\jdk1.8.0_111\jre\lib\ext\access-bridge-64.jar;C:\Program Files\Java\jdk1.8.0_111\jre\lib\ext\cldrdata.jar;C:\Program Files\Java\jdk1.8.0_111\jre\lib\ext\dnsns.jar;C:\Program Files\Java\jdk1.8.0_111\jre\lib\ext\jaccess.jar;C:\Program Files\Java\jdk1.8.0_111\jre\lib\ext\jfxrt.jar;C:\Program Files\Java\jdk1.8.0_111\jre\lib\ext\localedata.jar;C:\Program Files\Java\jdk1.8.0_111\jre\lib\ext\nashorn.jar;C:\Program Files\Java\jdk1.8.0_111\jre\lib\ext\sunec.jar;C:\Program Files\Java\jdk1.8.0_111\jre\lib\ext\sunjce_provider.jar;C:\Program Files\Java\jdk1.8.0_111\jre\lib\ext\sunmscapi.jar;C:\Program Files\Java\jdk1.8.0_111\jre\lib\ext\sunpkcs11.jar;C:\Program Files\Java\jdk1.8.0_111\jre\lib\ext\zipfs.jar;C:\Program Files\Java\jdk1.8.0_111\jre\lib\javaws.jar;C:\Program Files\Java\jdk1.8.0_111\jre\lib\jce.jar;C:\Program Files\Java\jdk1.8.0_111\jre\lib\jfr.jar;C:\Program Files\Java\jdk1.8.0_111\jre\lib\jfxswt.jar;C:\Program Files\Java\jdk1.8.0_111\jre\lib\jsse.jar;C:\Program Files\Java\jdk1.8.0_111\jre\lib\management-agent.jar;C:\Program Files\Java\jdk1.8.0_111\jre\lib\plugin.jar;C:\Program Files\Java\jdk1.8.0_111\jre\lib\resources.jar;C:\Program Files\Java\jdk1.8.0_111\jre\lib\rt.jar;C:\dev\eegproject\target\classes;C:\Users\kitcat-pc\.m2\repository\org\reflections\reflections\0.9.10\reflections-0.9.10.jar;C:\Users\kitcat-pc\.m2\repository\com\google\guava\guava\15.0\guava-15.0.jar;C:\Users\kitcat-pc\.m2\repository\org\javassist\javassist\3.19.0-GA\javassist-3.19.0-GA.jar;C:\Users\kitcat-pc\.m2\repository\com\google\code\findbugs\annotations\2.0.1\annotations-2.0.1.jar;C:\Users\kitcat-pc\.m2\repository\junit\junit\4.11\junit-4.11.jar;C:\Users\kitcat-pc\.m2\repository\org\hamcrest\hamcrest-core\1.3\hamcrest-core-1.3.jar;C:\Users\kitcat-pc\.m2\repository\com\1stleg\jnativehook\2.0.3\jnativehook-2.0.3.jar;C:\dev\eegproject\src\main\res\jna.jar;C:\Users\kitcat-pc\.m2\repository\org\mockito\mockito-all\1.10.19\mockito-all-1.10.19.jar;C:\Program Files (x86)\JetBrains\IntelliJ IDEA Community Edition 2016.3\lib\idea_rt.jar" com.intellij.rt.execution.application.AppMain com.ultron.eegcontroller.Application
Exception in thread "main" java.lang.UnsatisfiedLinkError: Unable to load library 'edk': Native library (win32-x86-64/edk.dll) not found in resource path ([file:/C:/Program%20Files/Java/jdk1.8.0_111/jre/lib/charsets.jar, file:/C:/Program%20Files/Java/jdk1.8.0_111/jre/lib/deploy.jar, file:/C:/Program%20Files/Java/jdk1.8.0_111/jre/lib/ext/access-bridge-64.jar, file:/C:/Program%20Files/Java/jdk1.8.0_111/jre/lib/ext/cldrdata.jar, file:/C:/Program%20Files/Java/jdk1.8.0_111/jre/lib/ext/dnsns.jar, file:/C:/Program%20Files/Java/jdk1.8.0_111/jre/lib/ext/jaccess.jar, file:/C:/Program%20Files/Java/jdk1.8.0_111/jre/lib/ext/jfxrt.jar, file:/C:/Program%20Files/Java/jdk1.8.0_111/jre/lib/ext/localedata.jar, file:/C:/Program%20Files/Java/jdk1.8.0_111/jre/lib/ext/nashorn.jar, file:/C:/Program%20Files/Java/jdk1.8.0_111/jre/lib/ext/sunec.jar, file:/C:/Program%20Files/Java/jdk1.8.0_111/jre/lib/ext/sunjce_provider.jar, file:/C:/Program%20Files/Java/jdk1.8.0_111/jre/lib/ext/sunmscapi.jar, file:/C:/Program%20Files/Java/jdk1.8.0_111/jre/lib/ext/sunpkcs11.jar, file:/C:/Program%20Files/Java/jdk1.8.0_111/jre/lib/ext/zipfs.jar, file:/C:/Program%20Files/Java/jdk1.8.0_111/jre/lib/javaws.jar, file:/C:/Program%20Files/Java/jdk1.8.0_111/jre/lib/jce.jar, file:/C:/Program%20Files/Java/jdk1.8.0_111/jre/lib/jfr.jar, file:/C:/Program%20Files/Java/jdk1.8.0_111/jre/lib/jfxswt.jar, file:/C:/Program%20Files/Java/jdk1.8.0_111/jre/lib/jsse.jar, file:/C:/Program%20Files/Java/jdk1.8.0_111/jre/lib/management-agent.jar, file:/C:/Program%20Files/Java/jdk1.8.0_111/jre/lib/plugin.jar, file:/C:/Program%20Files/Java/jdk1.8.0_111/jre/lib/resources.jar, file:/C:/Program%20Files/Java/jdk1.8.0_111/jre/lib/rt.jar, file:/C:/dev/eegproject/target/classes/, file:/C:/Users/kitcat-pc/.m2/repository/org/reflections/reflections/0.9.10/reflections-0.9.10.jar, file:/C:/Users/kitcat-pc/.m2/repository/com/google/guava/guava/15.0/guava-15.0.jar, file:/C:/Users/kitcat-pc/.m2/repository/org/javassist/javassist/3.19.0-GA/javassist-3.19.0-GA.jar, file:/C:/Users/kitcat-pc/.m2/repository/com/google/code/findbugs/annotations/2.0.1/annotations-2.0.1.jar, file:/C:/Users/kitcat-pc/.m2/repository/junit/junit/4.11/junit-4.11.jar, file:/C:/Users/kitcat-pc/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar, file:/C:/Users/kitcat-pc/.m2/repository/com/1stleg/jnativehook/2.0.3/jnativehook-2.0.3.jar, file:/C:/dev/eegproject/src/main/res/jna.jar, file:/C:/Users/kitcat-pc/.m2/repository/org/mockito/mockito-all/1.10.19/mockito-all-1.10.19.jar, file:/C:/Program%20Files%20(x86)/JetBrains/IntelliJ%20IDEA%20Community%20Edition%202016.3/lib/idea_rt.jar])
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:277)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:403)
	at com.sun.jna.Library$Handler.<init>(Library.java:147)
	at com.sun.jna.Native.loadLibrary(Native.java:502)
	at com.sun.jna.Native.loadLibrary(Native.java:481)
	at com.emotiv.Iedk.Edk.<clinit>(Edk.java:16)
	at com.ultron.eegcontroller.input.EEGHeadset.<init>(EEGHeadset.java:38)
	at com.ultron.eegcontroller.Application.main(Application.java:13)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)`

Hi, we are experiencing an issue with getting the Java examples to work on Windows 8 x64 with IntelliJ IDE as the edk.dll is not found. We have marked the lib/win64 as a native library, however this results in above error. Also, we have added the jna.jar file as a class library. We have ran the Java examples successfully on MacOS. Furthermore, from the stack trace it can be seen that the win64 dir has been set as a library path '-Djava.library.path=C:\dev\eegproject\src\main\res\win64' but we are still getting the missing edk.dll error.

When we take the edk.dll and jnidispatch.dll files from the jna.jar win32-x84-64 directory and move them in the win64 directory we are getting a different error.

`"C:\Program Files\Java\jdk1.8.0_111\bin\java" -Djava.library.path=C:\dev\eegproject\src\main\res\win64 -Didea.launcher.port=7537 "-Didea.launcher.bin.path=C:\Program Files (x86)\JetBrains\IntelliJ IDEA Community Edition 2016.3\bin" -Dfile.encoding=UTF-8 -classpath "C:\Program Files\Java\jdk1.8.0_111\jre\lib\charsets.jar;C:\Program Files\Java\jdk1.8.0_111\jre\lib\deploy.jar;C:\Program Files\Java\jdk1.8.0_111\jre\lib\ext\access-bridge-64.jar;C:\Program Files\Java\jdk1.8.0_111\jre\lib\ext\cldrdata.jar;C:\Program Files\Java\jdk1.8.0_111\jre\lib\ext\dnsns.jar;C:\Program Files\Java\jdk1.8.0_111\jre\lib\ext\jaccess.jar;C:\Program Files\Java\jdk1.8.0_111\jre\lib\ext\jfxrt.jar;C:\Program Files\Java\jdk1.8.0_111\jre\lib\ext\localedata.jar;C:\Program Files\Java\jdk1.8.0_111\jre\lib\ext\nashorn.jar;C:\Program Files\Java\jdk1.8.0_111\jre\lib\ext\sunec.jar;C:\Program Files\Java\jdk1.8.0_111\jre\lib\ext\sunjce_provider.jar;C:\Program Files\Java\jdk1.8.0_111\jre\lib\ext\sunmscapi.jar;C:\Program Files\Java\jdk1.8.0_111\jre\lib\ext\sunpkcs11.jar;C:\Program Files\Java\jdk1.8.0_111\jre\lib\ext\zipfs.jar;C:\Program Files\Java\jdk1.8.0_111\jre\lib\javaws.jar;C:\Program Files\Java\jdk1.8.0_111\jre\lib\jce.jar;C:\Program Files\Java\jdk1.8.0_111\jre\lib\jfr.jar;C:\Program Files\Java\jdk1.8.0_111\jre\lib\jfxswt.jar;C:\Program Files\Java\jdk1.8.0_111\jre\lib\jsse.jar;C:\Program Files\Java\jdk1.8.0_111\jre\lib\management-agent.jar;C:\Program Files\Java\jdk1.8.0_111\jre\lib\plugin.jar;C:\Program Files\Java\jdk1.8.0_111\jre\lib\resources.jar;C:\Program Files\Java\jdk1.8.0_111\jre\lib\rt.jar;C:\dev\eegproject\target\classes;C:\Users\kitcat-pc\.m2\repository\org\reflections\reflections\0.9.10\reflections-0.9.10.jar;C:\Users\kitcat-pc\.m2\repository\com\google\guava\guava\15.0\guava-15.0.jar;C:\Users\kitcat-pc\.m2\repository\org\javassist\javassist\3.19.0-GA\javassist-3.19.0-GA.jar;C:\Users\kitcat-pc\.m2\repository\com\google\code\findbugs\annotations\2.0.1\annotations-2.0.1.jar;C:\Users\kitcat-pc\.m2\repository\junit\junit\4.11\junit-4.11.jar;C:\Users\kitcat-pc\.m2\repository\org\hamcrest\hamcrest-core\1.3\hamcrest-core-1.3.jar;C:\Users\kitcat-pc\.m2\repository\com\1stleg\jnativehook\2.0.3\jnativehook-2.0.3.jar;C:\dev\eegproject\src\main\res\jna.jar;C:\Users\kitcat-pc\.m2\repository\org\mockito\mockito-all\1.10.19\mockito-all-1.10.19.jar;C:\Program Files (x86)\JetBrains\IntelliJ IDEA Community Edition 2016.3\lib\idea_rt.jar" com.intellij.rt.execution.application.AppMain com.ultron.eegcontroller.Application
Exception in thread "main" java.lang.UnsatisfiedLinkError: %1 is not a valid Win32 application.
	at com.sun.jna.Native.open(Native Method)
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:263)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:403)
	at com.sun.jna.Library$Handler.<init>(Library.java:147)
	at com.sun.jna.Native.loadLibrary(Native.java:502)
	at com.sun.jna.Native.loadLibrary(Native.java:481)
	at com.emotiv.Iedk.Edk.<clinit>(Edk.java:16)
	at com.ultron.eegcontroller.input.EEGHeadset.<init>(EEGHeadset.java:38)
	at com.ultron.eegcontroller.Application.main(Application.java:13)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)`

Can you please give us an advice how to solve this issue? Thank you! :)

**Comment by tanpv** [comment]
Hi MartinsIrbe,

Do you follow our guide document to working with Java here ?
https://github.com/Emotiv/community-sdk/blob/master/doc/How%20to%20run%20Java%20examples.pdf

Best Regard
Tan Pham

**Comment by MartinsIrbe** [comment]
@tanpv as my main OS is macOS Sierra I'm trying to make the application compatible with Windows 8. I have tried to follow the instructions, however I find it not very helpful as I'm not using Eclipse but IntelliJ. I'm not sure what is meant by the `PATH` variable. From my understanding we need to specify which version should be used, as in the jna.jar I can see there are some specific directories for specific versions. 
![image](https://cloud.githubusercontent.com/assets/13367583/22858264/b346817e-f0af-11e6-85a7-edb4de72cc64.png)

**Comment by ojsdude** [comment]
Just to add; I am working on the project with @MartinsIrbe and am the one using windows. I have tried specifying the PATH variable with both 32 and 64 bit and it's not working at all. We just don't understand why the setup is working perfectly on Mac and not on Windows (or Linux for that matter), even when we do the same thing. The error message that I am getting is as follows:

```
Exception in thread "JavaFX Application Thread" java.lang.UnsatisfiedLinkError: Unable to load library 'edk': Native library (win32-x86-64/edk.dll) not found in resource path ([file:/C:/Program%20Files/Java/jdk1.8.0_101/jre/lib/charsets.jar, file:/C:/Program%20Files/Java/jdk1.8.0_101/jre/lib/deploy.jar, file:/C:/Program%20Files/Java/jdk1.8.0_101/jre/lib/ext/access-bridge-64.jar, file:/C:/Program%20Files/Java/jdk1.8.0_101/jre/lib/ext/cldrdata.jar, file:/C:/Program%20Files/Java/jdk1.8.0_101/jre/lib/ext/dnsns.jar, file:/C:/Program%20Files/Java/jdk1.8.0_101/jre/lib/ext/jaccess.jar, file:/C:/Program%20Files/Java/jdk1.8.0_101/jre/lib/ext/jfxrt.jar, file:/C:/Program%20Files/Java/jdk1.8.0_101/jre/lib/ext/localedata.jar, file:/C:/Program%20Files/Java/jdk1.8.0_101/jre/lib/ext/nashorn.jar, file:/C:/Program%20Files/Java/jdk1.8.0_101/jre/lib/ext/sunec.jar, file:/C:/Program%20Files/Java/jdk1.8.0_101/jre/lib/ext/sunjce_provider.jar, file:/C:/Program%20Files/Java/jdk1.8.0_101/jre/lib/ext/sunmscapi.jar, file:/C:/Program%20Files/Java/jdk1.8.0_101/jre/lib/ext/sunpkcs11.jar, file:/C:/Program%20Files/Java/jdk1.8.0_101/jre/lib/ext/zipfs.jar, file:/C:/Program%20Files/Java/jdk1.8.0_101/jre/lib/javaws.jar, file:/C:/Program%20Files/Java/jdk1.8.0_101/jre/lib/jce.jar, file:/C:/Program%20Files/Java/jdk1.8.0_101/jre/lib/jfr.jar, file:/C:/Program%20Files/Java/jdk1.8.0_101/jre/lib/jfxswt.jar, file:/C:/Program%20Files/Java/jdk1.8.0_101/jre/lib/jsse.jar, file:/C:/Program%20Files/Java/jdk1.8.0_101/jre/lib/management-agent.jar, file:/C:/Program%20Files/Java/jdk1.8.0_101/jre/lib/plugin.jar, file:/C:/Program%20Files/Java/jdk1.8.0_101/jre/lib/resources.jar, file:/C:/Program%20Files/Java/jdk1.8.0_101/jre/lib/rt.jar, file:/C:/Users/Oliver/Desktop/CO600-Ultron-EEG-Drone-Control/target/classes/, file:/C:/Users/Oliver/.m2/repository/org/reflections/reflections/0.9.10/reflections-0.9.10.jar, file:/C:/Users/Oliver/.m2/repository/org/javassist/javassist/3.19.0-GA/javassist-3.19.0-GA.jar, file:/C:/Users/Oliver/.m2/repository/com/google/code/findbugs/annotations/2.0.1/annotations-2.0.1.jar, file:/C:/Users/Oliver/.m2/repository/com/1stleg/jnativehook/2.0.3/jnativehook-2.0.3.jar, file:/C:/Users/Oliver/Desktop/CO600-Ultron-EEG-Drone-Control/src/main/resources/jna.jar, file:/C:/Users/Oliver/.m2/repository/edu/wpi/rail/jrosbridge/0.2.0/jrosbridge-0.2.0.jar, file:/C:/Users/Oliver/.m2/repository/org/glassfish/javax.json/1.0.4/javax.json-1.0.4.jar, file:/C:/Users/Oliver/.m2/repository/org/glassfish/tyrus/tyrus-client/1.2.1/tyrus-client-1.2.1.jar, file:/C:/Users/Oliver/.m2/repository/org/glassfish/tyrus/tyrus-core/1.2.1/tyrus-core-1.2.1.jar, file:/C:/Users/Oliver/.m2/repository/org/glassfish/tyrus/tyrus-spi/1.2.1/tyrus-spi-1.2.1.jar, file:/C:/Users/Oliver/.m2/repository/javax/websocket/javax.websocket-api/1.0/javax.websocket-api-1.0.jar, file:/C:/Users/Oliver/.m2/repository/org/glassfish/tyrus/tyrus-websocket-core/1.2.1/tyrus-websocket-core-1.2.1.jar, file:/C:/Users/Oliver/.m2/repository/org/glassfish/tyrus/tyrus-container-grizzly/1.2.1/tyrus-container-grizzly-1.2.1.jar, file:/C:/Users/Oliver/.m2/repository/org/glassfish/grizzly/grizzly-framework/2.3.3/grizzly-framework-2.3.3.jar, file:/C:/Users/Oliver/.m2/repository/org/glassfish/grizzly/grizzly-http-server/2.3.3/grizzly-http-server-2.3.3.jar, file:/C:/Users/Oliver/.m2/repository/org/glassfish/grizzly/grizzly-http/2.3.3/grizzly-http-2.3.3.jar, file:/C:/Users/Oliver/.m2/repository/org/glassfish/grizzly/grizzly-rcm/2.3.3/grizzly-rcm-2.3.3.jar, file:/C:/Users/Oliver/.m2/repository/com/google/guava/guava/21.0/guava-21.0.jar, file:/C:/Users/Oliver/.m2/repository/net/java/jinput/jinput/2.0.6/jinput-2.0.6.jar, file:/C:/Users/Oliver/.m2/repository/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar, file:/C:/Users/Oliver/.m2/repository/net/java/jinput/jinput-platform/2.0.6/jinput-platform-2.0.6-natives-linux.jar, file:/C:/Users/Oliver/.m2/repository/net/java/jinput/jinput-platform/2.0.6/jinput-platform-2.0.6-natives-windows.jar, file:/C:/Users/Oliver/.m2/repository/net/java/jinput/jinput-platform/2.0.6/jinput-platform-2.0.6-natives-osx.jar, file:/C:/Users/Oliver/.m2/repository/org/mockito/mockito-all/1.10.19/mockito-all-1.10.19.jar, file:/C:/Users/Oliver/.m2/repository/org/loadui/testFx/3.1.2/testFx-3.1.2.jar, file:/C:/Users/Oliver/.m2/repository/org/hamcrest/hamcrest-all/1.3/hamcrest-all-1.3.jar, file:/C:/Users/Oliver/.m2/repository/junit/junit/4.11/junit-4.11.jar, file:/C:/Users/Oliver/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar, file:/C:/Program%20Files%20(x86)/JetBrains/IntelliJ%20IDEA%20Community%20Edition%202016.2.5/lib/idea_rt.jar])
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:277)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:403)
	at com.sun.jna.Library$Handler.<init>(Library.java:147)
	at com.sun.jna.Native.loadLibrary(Native.java:502)
	at com.sun.jna.Native.loadLibrary(Native.java:481)
	at com.emotiv.Iedk.Edk.<clinit>(Edk.java:16)
	at com.ultron.eegcontroller.model.input.EEGHeadset.<init>(EEGHeadset.java:44)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at com.ultron.eegcontroller.gui.util.ControllerHelper.getInputList(ControllerHelper.java:99)
	at com.ultron.eegcontroller.gui.controllers.InputController.initialize(InputController.java:34)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2548)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2441)
	at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2409)
	at com.ultron.eegcontroller.gui.controllers.BaseController.loadSceneInNode(BaseController.java:117)
	at com.ultron.eegcontroller.gui.controllers.WelcomeController.lambda$welcomeAnimationLoadScene$0(WelcomeController.java:39)
	at javafx.animation.Animation.impl_finished(Animation.java:1132)
	at javafx.animation.AnimationAccessorImpl.finished(AnimationAccessorImpl.java:49)
	at com.sun.scenario.animation.shared.SingleLoopClipEnvelope.timePulse(SingleLoopClipEnvelope.java:103)
	at javafx.animation.Animation.impl_timePulse(Animation.java:1102)
	at javafx.animation.Animation$1.lambda$timePulse$25(Animation.java:186)
	at java.security.AccessController.doPrivileged(Native Method)
	at javafx.animation.Animation$1.timePulse(Animation.java:185)
	at com.sun.scenario.animation.AbstractMasterTimer.timePulseImpl(AbstractMasterTimer.java:344)
	at com.sun.scenario.animation.AbstractMasterTimer$MainLoop.run(AbstractMasterTimer.java:267)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:506)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:490)
	at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$404(QuantumToolkit.java:319)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
	at java.lang.Thread.run(Thread.java:745)
```

Hopefully this can help.

**Comment by duytan90** [comment]
Hey @ojsdude, your error message said that it couldn't find the edk.dll file (maybe you need to check again project's Run Configuration on Environment tab). The relative path to edk.dll (../../bin/win64/) can also be replaced by absolute path (e.g. D:\<path to edk.dll file>) just to check loading library, but of course it's not recommended. I'm not sure about this settings on IntelliJ, but it should have the same configuration option https://www.jetbrains.com/help/idea/2016.3/path-variables.html.

![run configurations](https://cloud.githubusercontent.com/assets/10017143/23538309/01fdf252-0005-11e7-8d8c-c81e6682d79f.png)

Besides, I think MacOS uses [edk.framework](https://github.com/Emotiv/community-sdk/tree/master/lib/Mac/edk.framework) instead of edk.dll
