### ISSUE TITLE
Unable to run EmoStateLogger on MacOS X due to a linking issue

### ISSUE THREAD

**Issue by digigroup25** [Emotiv/community-sdk#192]
Environment:
Mac OSX Sierra (10.12.2)
Eclipse Neon.3
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)

I followed the instructions described here https://github.com/Emotiv/community-sdk/blob/master/doc/How%20to%20run%20Java%20examples.pdf

When I try to run EmoStateLogger in Eclipse, I get the following error.  I added the directory linux64 containing libedk.so* files to the classpath.  The problem is that it is looking for libedk.dylib which doesn't exist.   Please let me know how to resolve this issue.  Thank you in advance.

Exception in thread "main" java.lang.UnsatisfiedLinkError: Unable to load library 'edk': Native library (darwin/libedk.dylib) not found in resource path ([file:/Users/vlad/Documents/personal/Learning/emotiv/community-sdk-master/examples_basic/Java/linux64/, file:/Users/vlad/Documents/personal/Learning/emotiv/community-sdk-master/examples_basic/Java/bin/, file:/Users/vlad/Documents/personal/Learning/emotiv/community-sdk-master/include/java/, file:/Users/vlad/Documents/personal/Learning/emotiv/community-sdk-master/lib/java/jna.jar])
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:277)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:403)
	at com.sun.jna.Library$Handler.<init>(Library.java:147)
	at com.sun.jna.Native.loadLibrary(Native.java:502)
	at com.sun.jna.Native.loadLibrary(Native.java:481)
	at com.emotiv.Iedk.Edk.<clinit>(Edk.java:15)
	at com.emotiv.examples.EmoStateLogger.EmoStateLogger.main(EmoStateLogger.java:10)

**Comment by hoangphamemotiv** [comment]
Hi @digigroup25  please try the example with new SDK library v3.5.0

**Comment by SPineapple** [comment]
Hello, 
I have the same issue, and I'm also using Mac OSX Sierra (10.12.3),
I also downloaded sdk-3.5.0
and still didn't solve....
