### ISSUE TITLE
cannot locate symbol "rand" referenced by "libedk.so"

### ISSUE THREAD

**Issue by mneckoee** [Emotiv/community-sdk#319]
I want to run Android FacialExpression example but get this error: 
`com.emotiv.facialexpression E/AndroidRuntime: FATAL EXCEPTION: main
                                                                             Process: com.emotiv.facialexpression, PID: 16493
                                                                             java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "rand" referenced by "libedk.so"...
                                                                                 at java.lang.Runtime.loadLibrary(Runtime.java:371)
                                                                                 at java.lang.System.loadLibrary(System.java:606)
                                                                                 at com.emotiv.bluetooth.Emotiv.<clinit>(Emotiv.java:148)
                                                                                 at com.emotiv.dateget.EngineConnector.connectEngine(EngineConnector.java:87)
                                                                                 at com.emotiv.dateget.EngineConnector.<init>(EngineConnector.java:83)
                                                                                 at com.emotiv.dateget.EngineConnector.shareInstance(EngineConnector.java:77)
                                                                                 at com.emotiv.facialexpression.ContentActivity.onCreate(ContentActivity.java:84)
                                                                                 at android.app.Activity.performCreate(Activity.java:5343)
                                                                                 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1088)
                                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2343)
                                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2441)
                                                                                 at android.app.ActivityThread.access$900(ActivityThread.java:151)
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:110)
                                                                                 at android.os.Looper.loop(Looper.java:193)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5345)
                                                                                 at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                 at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
                                                                                 at dalvik.system.NativeStart.main(Native Method)`

**Comment by havietnam** [comment]
Hi @mneckoee ,
Can you tell me NDK version you are using?

**Comment by mneckoee** [comment]
I don't use NDK! because .so files are preCompiled. Where can I find the libedk.so source code?
