### ISSUE TITLE
undefined symbol: IEE_GetDebitInformation 

### ISSUE THREAD

**Issue by N0v0** [Emotiv/community-sdk#340]
Hello im working on a Raspberry Pi 3, I have been testing some of the examples and they seem to work fine but when y tried to run the ActivateLicense.py example a get an error when I call the "IEE_GetDebitInformation " , I got this :

```
pi@raspberrypi:~/Desktop/community-sdk-master/examples_extra_prime/Python $ python ActivateLicense.py
Traceback (most recent call last):
File "ActivateLicense.py", line 63, in <module>
IEE_GetDebitInformation = libre.IEE_GetDebitInformation
File "/usr/lib/python2.7/ctypes/__init__.py", line 375, in __getattr__ func = self.__getitem__(name)
File "/usr/lib/python2.7/ctypes/__init__.py", line 380, in __getitem__ func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /home/pi/Desktop/community-sdk-master/examples_extra_prime/Python/../../bin/armhf/libedk.so.3.3.3: undefined symbol: IEE_GetDebitInformation
```
 I tried all .so files from .so to .so.3.3.3 and non of them worked , I already managed to make the eeg_logger.py to work but im not getting any data because of the license activation , could you help me please!

**Comment by N0v0** [comment]
Ok thanks! Is there a way I can activate the license to use the eeg_logger.py program on the raspberry Pi 3?
