### ISSUE TITLE
Ptyhon for mac

### ISSUE THREAD

**Issue by kikuchikei** [Emotiv/community-sdk#357]
Hi.
I want to run examples_extra_prime / Python / eeg_logger.py on iMac.
Since eeg_logger.py does not correspond to darwin, it changed as follows.
```
# try :
#     if sys.platform.startswith('win32'):
#         libEDK = cdll.LoadLibrary("../../bin/win32/edk.dll")
#     elif sys.platform.startswith('linux'):
#         srcDir = os.getcwd()
#   if platform.machine().startswith('arm'):
#             libPath = srcDir + "/../../bin/armhf/libedk.so"
#   else:
#             libPath = srcDir + "/../../bin/linux64/libedk.so"
#         libEDK = CDLL(libPath)
#     else:
#         raise Exception('System not supported.')
# except :
#     print 'Error : cannot load dll lib' 

libEDK = cdll.LoadLibrary("../../lib/Mac/edk.framework/edk")
```
However, the following error occurred. I ran it line by line
```
(py27_32) r237-89-24-133:Python eeg$ python
Python 2.7.10 |Continuum Analytics, Inc.| (default, Aug 23 2015, 22:59:44) 
[GCC 4.2.1 (Apple Inc. build 5577)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>> import ctypes
>> libEDK = ctypes.cdll.LoadLibrary("../../lib/Mac/edk.framework/edk")
Traceback (most recent call last):

  File "", line 1, in 
  File "/Users/eeg/anaconda3/envs/py27_32/lib/python2.7/ctypes/init__.py", line 443, in LoadLibrary return self.dlltype(name) File "/Users/eeg/anaconda3/envs/py27_32/lib/python2.7/ctypes/__init_.py", line 365, in __init
  self._handle = _dlopen(self._name, mode)

OSError: dlopen(../../lib/Mac/edk.framework/edk, 6): no suitable image found. Did find:

  ../../lib/Mac/edk.framework/edk: mach-o, but wrong architecture
  /Users/eeg/Research/emotiv/community-sdk-master/lib/Mac/edk.framework/edk: mach-o, but wrong architecture

>>
```
Is it impossible to run this sample code on iMac? or is it wrong to refer to edk?
Please tell me if my English is wrong. 
thanks.

macOS High Sierra 10.13.6
iMac (Retina 5K, 27-inch, 2017)
python2.7 (32bit) for anaconda3

**Comment by kikuchikei** [comment]
I also looked up python 3.
Reference to sdk worked fine, but there were other errors. (Segmentation fault: 11)

```
(py36) r237-89-24-133:Python eeg$ python eeg_logger.py 
=================================================================== 
Example to show how to log EEG Data from EmoEngine/EmoComposer. 
=================================================================== 
Press '1' to start and connect to the EmoEngine 
Press '2' to connect to the EmoComposer 
>> 1 
0 
Start receiving EEG Data! Press any key to stop logging... 
Buffer size in secs: 
Segmentation fault: 11 
(py27) r237-89-24-133:Python eeg$
```

I do not need either python 2 or python 3, so I want to operate on macOS.
Help !!

**Comment by kikuchikei** [comment]
I am going to try what I can do. Please tell us what!!
