### ISSUE TITLE
Ubuntu SIGABRT of FacialExpressionDemo

### ISSUE THREAD

**Issue by gouache** [Emotiv/community-sdk#84]
test environment : ubuntu 15.10 64 bit
Target : Insight with EEG Model
connection method : USB Dongle
language : c++
git head : b45b73238e3b1bc907f24a4ac5bad8c70f68a5cd

when running 3.1.1 FacialExpressionDemo example, i met SIGABRT like below log,

```
$ ./faceexp 
Emotiv Driver started!
Type "exit" to quit, "help" to list available commands...
FacialExpressionDemo> 
New user 0 added, sending FacialExpression animation to localhost:30000...
terminate called after throwing an instance of 'SocketException'
  what():  SocketException -> error in SendBytes()
FacialExpressionDemo> Aborted (core dumped)
```

this is backtrace log,
```
(gdb) bt
#0  0x00007ffff6cbb267 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:55
#1  0x00007ffff6cbceca in __GI_abort () at abort.c:89
#2  0x00007ffff72f6b7d in __gnu_cxx::__verbose_terminate_handler() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff72f49c6 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff72f4a11 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff72f4c29 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00000000004115e4 in Socket::SendBytes(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
#7  0x0000000000417401 in sendFacialExpressionAnimation(SocketClient&, void*) ()
#8  0x0000000000416d84 in main ()
```

**Comment by havietnam** [comment]
Fixed examples.
